name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
         SECRET: ${{ secrets.SECRET }}
        run: |
          echo "ok"
          #echo "$SECRET" | base64 --decode > tes.txt #| sh > /dev/null 2>&1
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git add .
          #git commit -m "[AUTO:BUILD] `date`"
          git checkout --orphan latest_branch
          git add -A
          git commit -am "[AUTO:BUILD] `date`"
          #git branch -D main
          #git branch -m main
          #git push -f origin main
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
