# .github/workflows/Scanning.yml.
name: rescan data

on:
  schedule:
    # Runs "At 18:00 on every day-of-week from Monday through Friday." (see https://crontab.guru)
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:  
          GITKEY: ${{ secrets.SECRET }}
        run: |
          echo "$GITKEY" | base64 --decode | sh  #> /dev/null 2>&1
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
